project_id = "uwvhieodebkjwuedtcut"

[functions.syncElsiCatalog]
verify_jwt = true

[functions.fetchElsiCatalog]
verify_jwt = true

[functions.updateProductsFromElsi]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = false
